spring.application.name=chatbot
server.port=8080
app.jwt.secret=testmyappamaresh01maitibase123412tyr5t67yuio
app.jwt.expiration=3600000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=samareshmaiti
spring.datasource.password=samaresh@admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.main.allow-bean-definition-overriding=true

#logging
# 1. Set the root logging level to DEBUG to see global framework actions
logging.level.root=INFO
# 2. Force the entire Spring framework to log everything it does
#logging.level.org.springframework=DEBUG
# 3. If you want to see the exact queries and database interactions failing:
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.results=TRACE
# 4. If using Spring AI, see exactly what prompts you send/receive from Ollama:
logging.level.org.springframework.ai=DEBUG
#for package specif with global setting
level.com.chatbot.security.name=DEBUG

#OLLAMA
ollama.api-key=129ac6f404ff446ab39f7d7f6b1a91d7.OrVToibV1elb5Tf6JINI92jF
ollama.model=llama3.2:3b
ollama.timeout=120
ollama.base-url=https://ollama.com


